INSERT INTO civirule_event (name, label, object_name, op, class_name, created_date, created_user_id)
VALUES
  ('new_activity', 'New Activity', 'Activity', 'create', null,  CURDATE(), 1),
  ('changed_activity', 'Changed Activity', 'Activity', 'edit', null, CURDATE(), 1),
  ('deleted_activity', 'Deleted Activity', 'Activity', 'delete', null, CURDATE(), 1),
  ('new_address', 'New Address', 'Address', 'create', null,  CURDATE(), 1),
  ('changed_address', 'Changed Address', 'Address', 'edit', null, CURDATE(), 1),
  ('deleted_address', 'Deleted Address', 'Address', 'delete', null, CURDATE(), 1),
  ('new_case', 'New Case', 'Case', 'create', null,  CURDATE(), 1),
  ('changed_case', 'Changed Case', 'Case', 'edit', null, CURDATE(), 1),
  ('deleted_case', 'Deleted Case', 'Case', 'delete', null, CURDATE(), 1),
  ('new_contact', 'New Contact (any type)', 'Contact', 'create', null,  CURDATE(), 1),
  ('changed_contact', 'Changed Contact (any type)', 'Contact', 'edit', null, CURDATE(), 1),
  ('deleted_contact', 'Deleted Contact (any type)', 'Contact', 'delete', null, CURDATE(), 1),
  ('trashed_contact', 'Trashed Contact (any type)', 'Contact', 'delete', null, CURDATE(), 1),
  ('restored_contact', 'Restored Contact (any type)', 'Contact', 'delete', null, CURDATE(), 1),
  ('new_individual', 'New Individual', 'Individual', 'create', null,  CURDATE(), 1),
  ('changed_individual', 'Changed Individual', 'Individual', 'edit', null, CURDATE(), 1),
  ('deleted_individual', 'Deleted Individual', 'Individual', 'delete', null, CURDATE(), 1),
  ('trashed_individual', 'Trashed Individual', 'Individual', 'delete', null, CURDATE(), 1),
  ('restored_individual', 'Restored Individual', 'Individual', 'delete', null, CURDATE(), 1),
  ('new_household', 'New Household', 'Household', 'create', null,  CURDATE(), 1),
  ('changed_household', 'Changed Household', 'Household', 'edit', null, CURDATE(), 1),
  ('deleted_household', 'Deleted Household', 'Household', 'delete', null, CURDATE(), 1),
  ('trashed_household', 'Trashed Household', 'Household', 'delete', null, CURDATE(), 1),
  ('restored_household', 'Restored Household', 'Household', 'delete', null, CURDATE(), 1),
  ('new_organization', 'New Household', 'Household', 'create', null,  CURDATE(), 1),
  ('changed_organization', 'Changed Household', 'Household', 'edit', null, CURDATE(), 1),
  ('deleted_organization', 'Deleted Household', 'Household', 'delete', null, CURDATE(), 1),
  ('trashed_organization', 'Trashed Household', 'Household', 'delete', null, CURDATE(), 1),
  ('restored_organization', 'Restored Household', 'Household', 'delete', null, CURDATE(), 1);

INSERT INTO civirule_event (name, label, object_name, op, class_name, created_date, created_user_id)
VALUES
  ('new_contribution', 'New Contribution', 'Contribution', 'create', null,  CURDATE(), 1),
  ('changed_contribution', 'Changed Contribution', 'Contribution', 'edit', null, CURDATE(), 1),
  ('deleted_contribution', 'Deleted Contribution', 'Contribution', 'delete', null, CURDATE(), 1),
  ('new_contribution_recur', 'New Recurring Contribution', 'ContributionRecur', 'create', null,  CURDATE(), 1),
  ('changed_contribution_recur', 'Changed Recurring Contribution', 'ContributionRecur', 'edit', null, CURDATE(), 1),
  ('deleted_contribution_recur', 'Deleted Recurring Contribution', 'ContributionRecur', 'delete', null, CURDATE(), 1),
  ('new_emailaddress', 'New Email-address', 'Email', 'create', null,  CURDATE(), 1),
  ('changed_emailaddress', 'Changed Email-address', 'Email', 'edit', null, CURDATE(), 1),
  ('deleted_emailaddress', 'Deleted Email-address', 'Email', 'delete', null, CURDATE(), 1),
  ('new_entity_tag', 'Entity Tagged', 'EntityTag', 'create', null,  CURDATE(), 1),
  ('changed_entity_tag', 'Entity Tag Changed', 'EntityTag', 'edit', null, CURDATE(), 1),
  ('deleted_entity_tag', 'Entity Tag Removed', 'EntityTag', 'delete', null, CURDATE(), 1),
  ('new_event', 'New Event', 'Event', 'create', null,  CURDATE(), 1),
  ('changed_event', 'Changed Event', 'Event', 'edit', null, CURDATE(), 1),
  ('deleted_event', 'Deleted Event', 'Event', 'delete', null, CURDATE(), 1),
  ('new_grant', 'New Grant', 'Grant', 'create', null,  CURDATE(), 1),
  ('changed_grant', 'Changed Grant', 'Grant', 'edit', null, CURDATE(), 1),
  ('deleted_grant', 'Deleted Grant', 'Grant', 'delete', null, CURDATE(), 1),
  ('new_group', 'New Group', 'Group', 'create', null,  CURDATE(), 1),
  ('changed_group', 'Changed Group', 'Group', 'edit', null, CURDATE(), 1),
  ('deleted_group', 'Deleted Group', 'Group', 'delete', null, CURDATE(), 1),
  ('new_group_contact', 'Added Contact to Group', 'GroupContact', 'create', null,  CURDATE(), 1),
  ('deleted_group_contact', 'Removed Contact from GroupContact', 'Group', 'delete', null, CURDATE(), 1),
  ('new_membership', 'New Membership', 'Membership', 'create', null,  CURDATE(), 1),
  ('changed_membership', 'Changed Membership', 'Membership', 'edit', null, CURDATE(), 1),
  ('deleted_membership', 'Deleted Membership', 'Membership', 'delete', null, CURDATE(), 1),
  ('new_membership_payment', 'New Membership Payment', 'MembershipPayment', 'create', null,  CURDATE(), 1),
  ('changed_membership_payment', 'Changed Membership Payment', 'MembershipPayment', 'edit', null, CURDATE(), 1),
  ('deleted_membership_payment', 'Deleted Membership Payment', 'MembershipPayment', 'delete', null, CURDATE(), 1);

INSERT INTO civirule_event (name, label, object_name, op, class_name, created_date, created_user_id)
VALUES
  ('new_participant', 'New Event Participant', 'Participant', 'create', null,  CURDATE(), 1),
  ('changed_participant', 'Changed Event Participant', 'Participant', 'edit', null, CURDATE(), 1),
  ('deleted_participant', 'Deleted Event Participant', 'Participant', 'delete', null, CURDATE(), 1),
  ('new_participant_payment', 'New Payment for Event Participant', 'ParticipantPayment', 'create', null,  CURDATE(), 1),
  ('changed_participant_payment', 'Changed Payment for Event Participant', 'ParticipantPayment', 'edit', null, CURDATE(), 1),
  ('deleted_participant_payment', 'Deleted Payment for Event Participant', 'ParticipantPayment', 'delete', null, CURDATE(), 1),
  ('new_phone', 'New Phonenumber', 'Phone', 'create', null,  CURDATE(), 1),
  ('changed_phone', 'Changed Phonenumber', 'Phone', 'edit', null, CURDATE(), 1),
  ('deleted_phone', 'Deleted Phonenumber', 'Phone', 'delete', null, CURDATE(), 1),
  ('new_pledge', 'New Pledge', 'Pledge', 'create', null,  CURDATE(), 1),
  ('changed_pledge', 'Changed Pledge', 'Pledge', 'edit', null, CURDATE(), 1),
  ('deleted_pledge', 'Deleted Pledge', 'Pledge', 'delete', null, CURDATE(), 1),
  ('new_pledge_payment', 'New Pledge Payment', 'PledgePayment', 'create', null,  CURDATE(), 1),
  ('changed_pledge_payment', 'Changed Pledge Payment', 'PledgePayment', 'edit', null, CURDATE(), 1),
  ('deleted_pledge_payment', 'Deleted Pledge Payment', 'PledgePayment', 'delete', null, CURDATE(), 1),
  ('new_relationship', 'New Relationship', 'Relationship', 'create', null,  CURDATE(), 1),
  ('changed_relationship', 'Changed Relationship', 'Relationship', 'edit', null, CURDATE(), 1),
  ('deleted_relationship', 'Deleted Relationship', 'Relationship', 'delete', null, CURDATE(), 1),
  ('new_tag', 'New Tag', 'Tag', 'create', null,  CURDATE(), 1),
  ('changed_tag', 'Changed Tag', 'Tag', 'edit', null, CURDATE(), 1),
  ('deleted_tag', 'Deleted Tag', 'Tag', 'delete', null, CURDATE(), 1);